PsicoCare/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('payments/', include('payments.urls')),
    path('scheduling/', include('scheduling.urls')),
    path('google_meet/', include('google_meet.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from .views import index, perfil, registro, ingresar, home, recuperar_contrasena, perfil_configurar, test, matching, pagos, registro_psicologo, soporte, resena, psicologo, agendar
from core import views

urlpatterns = [
    path('', index, name='index'),
    path('perfil', perfil, name='perfil'),
    path('test', test, name='test'),
    path('perfil-configurar', perfil_configurar, name='perfil_configurar'),
    path('registro', registro, name='registro'),
    path('registro_psicologo', registro_psicologo, name='registro_psicologo'),
    path('ingresar', ingresar, name='ingresar'),
    path('home', home, name='home'),
    # path('videollamada', videollamada, name='videollamada'),
    # path('crear-sesion', views.crear_sesion, name='crear_sesion'),
    # path('listar-sesiones', views.listar_sesiones, name='listar_sesiones'),
    # path('editar-sesion/<str:event_id>/', views.editar_sesion, name='editar_sesion'),
    # path('detalle-sesion/<str:event_id>/', views.detalle_sesion, name='detalle_sesion'),
    # path('eliminar-sesion/<str:event_id>/', views.eliminar_sesion, name='eliminar_sesion'),
    path('recuperar_contrasena', recuperar_contrasena, name='recuperar_contrasena'),
    path('matching', matching, name='matching'),
    path('agendar', agendar, name='agendar'),
    path('psicologo/<psico_id>/<usu_id>',psicologo, name='psicologo'),
    path("accounts/", include("django.contrib.auth.urls")),
    path('pagos', pagos, name='pagos'),
    # path('chat/<int:conversation_id>/', views.chat_view, name='chat_view'),
    path('chat', views.chat_view, name='chat'),
    path('soporte', soporte, name='soporte'),
    path('resena', resena, name='resena'),
    path('logout', views.logout_view, name='logout'),


]

core/forms.py
from django import forms
from django.forms import ModelForm, fields, Form, ModelMultipleChoiceField
from .models import Test, Psicologo, Usuario, Generopsicologo, Tiposesion, Corrientepsicologica, Rangoetario, Rangoprecio, Motivosesion, Coberturasalud, Diagnostico, Resena
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.shortcuts import get_object_or_404
from django.contrib.auth.forms import UserCreationForm
# from captcha.fields import ReCaptchaField
# from captcha.widgets import ReCaptchaV2Checkbox



form_hidden = {'class': 'd-none'}
form_select = {'class': 'form-select'}
form_control = {'class': 'form-control'}
form_text_area = {'class': 'form-control', 'rows': '1'}
form_file = {'class': 'form-control-file', 'title': 'Debe subir una imagen'}
form_check = {'class': 'form-check-input'}
form_password = {'class': 'form-control text-danger'}

GENERO = (("1","Mujer"),("2","Hombre"),("3","Otro"))
class FormRegistro (UserCreationForm): 
    # username = forms.CharField(
    #     max_length=100, 
    #     required=True, 
    #     label='nombre de usuario',
    #     widget=forms.TextInput(attrs={'placeholder': 'Ingresa Usuario'}),
    # )
    # first_name = forms.CharField(
    #     max_length=100, 
    #     required=True, 
    #     label='nombres',
    #     widget=forms.TextInput(attrs={'placeholder': 'Ingresa nombres'}),
    # )

    # last_name = forms.CharField(
    #     max_length=100, 
    #     required=True, 
    #     label='apellido paterno',
    #     widget=forms.TextInput(attrs={'placeholder': 'Ingresa apellido paterno'}),
    # )

    apellido_materno = forms.CharField(
        max_length=100, 
        required=True, 
        label='apellido materno',
        widget=forms.TextInput(attrs={'placeholder': ''}),
    )

    genero_idgenero = forms.MultipleChoiceField(
        required=True, 
        label='Género',
        widget=forms.Select,
        choices=GENERO,
    )

    # email = forms.EmailField(
    #     required=True,
    #     label='correo',
    #     widget=forms.EmailInput(attrs={'placeholder': 'Ingresa correo'})
    # )

    password = forms.CharField(
        max_length=20, 
        required=True, 
        label='contraseña',
        widget=forms.PasswordInput (attrs={'placeholder': ''}),
    )

    password2= forms.CharField(
        label='confirmar contraseña',
        widget=forms.PasswordInput (attrs={'placeholder': ''}),
    )

    class Meta:
        model = User
        fields = ['username','first_name', 'last_name', 'apellido_materno', 'email', 'genero_idgenero', 'password', 'password2']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(form_control)
        self.fields['first_name'].widget.attrs.update(form_control)
        self.fields['last_name'].widget.attrs.update(form_control)
        self.fields['email'].widget.attrs.update(form_control)
        self.fields['password'].widget.attrs.update(form_control)
        self.fields['password2'].widget.attrs.update(form_control)




GENERO = (("1","Mujer"),("2","Hombre"),("3","Otro"))
class FormRegistroPsi (UserCreationForm): 
    # username = forms.CharField(
    #     max_length=100, 
    #     required=True, 
    #     label='nombre de usuario',
    #     widget=forms.TextInput(attrs={'placeholder': 'Ingresa Usuario'}),
    # )
    # first_name = forms.CharField(
    #     max_length=100, 
    #     required=True, 
    #     label='nombres',
    #     widget=forms.TextInput(attrs={'placeholder': 'Ingresa nombres'}),
    # )

    # last_name = forms.CharField(
    #     max_length=100, 
    #     required=True, 
    #     label='apellido paterno',
    #     widget=forms.TextInput(attrs={'placeholder': 'Ingresa apellido paterno'}),
    # )

    apellido_materno = forms.CharField(
        max_length=100, 
        required=True, 
        label='apellido materno',
        widget=forms.TextInput(attrs={'placeholder': ''}),
    )

    genero_idgenero = forms.MultipleChoiceField(
        required=True, 
        label='Género',
        widget=forms.Select,
        choices=GENERO,
    )

    # email = forms.EmailField(
    #     required=True,
    #     label='correo',
    #     widget=forms.EmailInput(attrs={'placeholder': 'Ingresa correo'})
    # )

    password = forms.CharField(
        max_length=20, 
        required=True, 
        label='contraseña',
        widget=forms.PasswordInput (attrs={'placeholder': ''}),
    )

    password2= forms.CharField(
        label='confirmar contraseña',
        widget=forms.PasswordInput (attrs={'placeholder': ''}),
    )

    licencia= forms.CharField(
        label='Número de registro de licencia',
        widget=forms.TextInput(attrs={'placeholder': ''}),
    )

    class Meta:
        model = User
        fields = ['username','first_name', 'last_name', 'apellido_materno', 'genero_idgenero', 'email', 'password', 'password2', 'licencia']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(form_control)
        self.fields['first_name'].widget.attrs.update(form_control)
        self.fields['last_name'].widget.attrs.update(form_control)
        self.fields['email'].widget.attrs.update(form_control)
        self.fields['password'].widget.attrs.update(form_control)
        self.fields['password2'].widget.attrs.update(form_control)

class IngresarForm(Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Ingresar Usuario'}), label="Username")
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Ingresa tu contraseña'}), label="Contraseña")
    class Meta:
        model = Usuario
        fields = ['username', 'password']

class PasswordResetForm(Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Ingresar correo'}), label="Correo")
    class Meta:
        model = Usuario
        fields = ['email']

# FORMS PERFIL

class DatosPersonalesForm (forms.ModelForm): 
    edit_per = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    username = forms.CharField(
        max_length=100, 
        required=True, 
        label='nombre de usuario',
        widget=forms.TextInput(attrs={'placeholder': 'Ingresa nombre de usuario'}),
    )

    first_name = forms.CharField(
        max_length=100, 
        required=True, 
        label='nombres',
        widget=forms.TextInput(attrs={'placeholder': 'Ingresa nombres'}),
    )

    last_name = forms.CharField(
        max_length=100, 
        required=True, 
        label='apellido paterno',
        widget=forms.TextInput(attrs={'placeholder': 'Ingresa apellido paterno'}),
    )

    apellido_materno = forms.CharField(
        max_length=100, 
        required=True, 
        label='apellido materno',
        widget=forms.TextInput(attrs={'placeholder': 'Ingresa apellido materno'}),
    )

    email = forms.EmailField(
        required=True,
        label='correo',
        widget=forms.EmailInput(attrs={'placeholder': 'Ingresa correo'})
    )

    password = forms.CharField(
        max_length=20, 
        required=True, 
        label='contraseña',
        widget=forms.PasswordInput (attrs={'placeholder': 'Ingresa contraseña'}),
    )
    class Meta:
        model = Usuario
        fields = ['username', 'first_name', 'last_name', 'apellido_materno', 'email', 'password']



EDAD_OP = (("1","Infanto-juvenil"),("2","Adultos"),("3","Adulto mayor"))
PCORRIENTE_OP=(("1","Cognitivo-Conductual"),("2","Psicoanálisis"),("3","Sistémica"),("4","Humanista"),("5","Breve"),("6","Feminista"))
PRECIO_OP=(("1","$0-$10000"),("2","$10000-$15000"),("3","$15000-$20000"),("4","$25000-$30000"),("5","$30000-$35000"),("6","$35000-$40000"),
                ("7","$40000-$45000"),("8","$45000-$50000"),("9","+$50000"))
COBERTURA_OP=(("1","Fonasa"),("2","Isapre"),("3","Otro"),("4","Ninguno"))

class DatosProfesionalesForm (forms.ModelForm): 
    edit_prof = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    rango_etario = forms.MultipleChoiceField(
        required=True, 
        label='Rango etario',
        widget=forms.Select,
        choices=EDAD_OP,
    )

    corriente_psicologica = forms.MultipleChoiceField(
        required=True, 
        widget=forms.Select,
        choices=PCORRIENTE_OP,
    )

    esp_diagnostica = forms.CharField(
        max_length=100, 
        required=True, 
        label='Especialidad diagnóstica',
        widget=forms.TextInput(attrs={'placeholder': 'Ingrese especialidad diagnóstica'}),
    )

    areas_trabajo = forms.CharField(
        max_length=100, 
        required=True, 
        label='Áreas de trabajo',
        widget=forms.TextInput(attrs={'placeholder': 'Ingresa áreas con las que trabaja'}),
    )

    rango_precio = forms.MultipleChoiceField(
        required=True, 
        label='Rango de precio',
        widget=forms.Select,
        choices=PRECIO_OP,
    )

    cobertura_aceptada = forms.MultipleChoiceField(
        required=True, 
        label='Cobertura de salud que acepta',
        widget=forms.Select,
        choices=COBERTURA_OP,
    )
    numeroregistrolicencia  = forms.CharField(
        max_length=100, 
        required=True, 
        label='Número registro de licencia',
        widget=forms.TextInput(attrs={'placeholder': 'Ingresa número registro licencia'}),
    )

    class Meta:
        model = Psicologo
        fields = ['rango_etario','corriente_psicologica','esp_diagnostica','areas_trabajo','rango_precio','cobertura_aceptada','numeroregistrolicencia']

class EliminarForm(Form):
    eliminar_cuenta = forms.BooleanField(widget=forms.HiddenInput, initial=True)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Ingresa tu contraseña'}), label="Contraseña")
    
    class Meta:
        model = Usuario
        fields = ['password']

# FORMS PERFIL
from django import forms

core/templates/core/agendar.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <h1>Disponibilidad horaria</h1>
        <button><a href="{% url 'create_schedule' %}"> crear agenda </a></button>
    </div>

{% endblock content %}

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'core/css/stylesheet.css' %}">
    <link rel="stylesheet" href="{% static 'scheduling/css/stylesheet.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" /> 

</head>
<body class="fondo">
    {% block navbar %}
        <div class="container-fluid">
            <div class="logops">
                {% if not user.is_authenticated %}
                <a class="navbar-icon" href="{% url 'index' %}">
                <h2>PsicoCare</h2>
                </a>
                {% endif %}
                {% if user.is_authenticated %}
                <a class="navbar-icon" href="{% url 'home' %}">
                <h2>PsicoCare</h2>
                </a>
                {% endif %}
            </div>
                {% if not user.is_authenticated %}
                <div class="nav-options">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'index' %}"> Inicio </a>
                    </li>
                    <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}"> ¿Cómo funciona? </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'index' %}"> Nosotros </a>
                    </li>
                </div>
                <div class="btns">
                    <li>
                        <a class="nav-btn" href="{% url 'ingresar' %}">Iniciar sesión</a>
                    </li>
                    <li>
                        <a class="nav-btn2" href="{% url 'registro' %}">Regístrate</a>
                    </li>
                </div>
                {% endif %}

                {% if user.is_authenticated %}
                <div class="navbar-up">
                    <div class="btns">
                        <li>
                             <a class="nav-btn2" href="{% url 'registro' %}"><i class="bi bi-box-arrow-right"></i></a>
                        </li>
                    </div>
                </div>
                <div class="navbar-left">
                    <i class="bi bi-house"></i>
                    <i class="bi bi-heart"></i>
                    <i class="bi bi-envelope"></i>
                    <i class="bi bi-bell-fill"></i>
                </div>

                {% endif %}
        </div>
    {% endblock navbar %}

    <div class="content m-3">
        {% block content %}
        
        {% endblock content %}
    </div>

    <!--Validadores-->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N"
    crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.10.0/jquery.validate.min.js"></script>
<script src="{% static 'core/js/scripts.js'%}"></script>
<script src="{% static 'core/js/perfil.js'%}"></script>
<script src="{% static 'core/js/test-matching.js'%}"></script>
</body>

</html>

core/templates/core/confirmacion_eliminar_sesion.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h2>Evento Eliminado</h2>
    <p>El evento ha sido eliminado correctamente.</p>
</div>
{% endblock %}

core/templates/core/crear_sesion.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3 mt-5">
            <h2 class="text-center">Crear Nueva Sesión</h2>
            <form method="post" action="{% url 'crear_sesion' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="summary" class="form-label">Resumen:</label>
                    <input type="text" class="form-control" id="summary" name="summary" required>
                </div>
                <div class="mb-3">
                    <label for="start_time" class="form-label">Hora de inicio:</label>
                    <input type="text" class="form-control" id="start_time" name="start_time" placeholder="YYYY-MM-DDTHH:MM:SS±HH:MM" required>
                </div>
                <div class="mb-3">
                    <label for="end_time" class="form-label">Hora de fin:</label>
                    <input type="text" class="form-control" id="end_time" name="end_time" placeholder="YYYY-MM-DDTHH:MM:SS±HH:MM" required>
                </div>
                
                <div class="mb-3">
                    <label for="timezone" class="form-label">Zona horaria:</label>
                    <input type="text" class="form-control" id="timezone" name="timezone" required>
                </div>
                <div class="mb-3">
                    <label for="attendees" class="form-label">Asistentes:</label>
                    <input type="text" class="form-control" id="attendees" name="attendees">
                </div>
                <button type="submit" class="btn btn-primary">Crear Evento</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

core/templates/core/detalle_sesion.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h2>Detalles de la Sesión</h2>
    <ul>
        <li><strong>ID Sesión:</strong> {{ event_details.id }}</li>
        <li><strong>Resumen:</strong> {{ event_details.summary }}</li>
        <li><strong>Hora de inicio:</strong> {{ event_details.start.dateTime }} ({{ event_details.start.timeZone }})</li>
        <li><strong>Hora de fin:</strong> {{ event_details.end.dateTime }} ({{ event_details.end.timeZone }})</li>
        <li><strong>Estado:</strong> {{ event_details.status }}</li>
    </ul>
</div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <div class="background">
        <img src="{% static 'core/img/background1.jpg' %}" alt="background">

    </div>
    <div class="text-box">
        <h1>Bienvenido/a a PsicoCare, tu destino confiable para el bienestar mental.</h1>
        <p>Con nuestra plataforma de terapia en línea, te ofrecemos acceso rápido y conveniente a una red de 
            psicólogos profesionales, listos para brindarte el apoyo y la orientación que necesitas, todo desde 
            la comodidad y privacidad de tu hogar. Descubre cómo podemos ayudarte a comenzar tu viaje hacia una mente 
            más sana y equilibrada hoy mismo.</p>
        <button class="start-button"> <a href="{% url 'test' %}">Comienza aquí</a></button>
    </div>

{% endblock content %}

core/templates/core/listar_sesiones.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <h1>Listado de Sesiones</h1>
    sesión de ejemplo $50000 <button class="btn btn-primary" id="perfil-homebtn"><a href="{% url 'pagos' %}">pagar</a></button>
    {% if sesiones %}
    <ul class="list-group">
        {% for sesion in sesiones %}
            <li class="list-group-item">{{ sesion.id }} - {{ sesion.summary }} - {{ sesion.start.dateTime }} - {{ sesion.status }} - {{ sesion.htmlLink }} <button type="button" class="btn-pago" name="pago"><a href="{% url 'init_transaction' %}">realizar pago</a></button></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No se encontraron sesiones.</p>
    {% endif %}
    
</div>

<style>
    a {
        text-decoration: none;
        font-family: 'Lexend', sans-serif;
        font-style: normal;
        font-weight: 500;
        color: black;
        }
    .list-group {
        display: inline-block;
        padding-inline: 160px;
        margin-left: 90px;
        margin-top: 25px;
    }
    .btn-pago {
        display: inline-block;
        margin-left: 20px;
        margin-top: 10px;
    }
</style>
{% endblock content %}

core/templates/core/soporte.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <h1>Envía comentarios o preguntas</h1>
        
    </div>

{% endblock content %}

core/templates/core/test.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<div id="volver-inicio">
    <a href="{% url 'index' %}"><i class="bi bi-arrow-left-short" id="flecha"></i></a> TEST
</div>

{% comment %} <form method="POST" enctype="multipart/form-data" id="FormTestPaciente" class="FormTestPaciente">
    {% csrf_token %}
    <div class="test-paciente">
        <div class="content-test" id="content-1" data-id='1' style="display: block;">
            <h3>¿Tienes alguna preferencia sobre el género de tu psicólogo/a?</h3>
            <div class="form-group">
                <select name="pref_genero" id="id_pref_genero" class="form-control">
                    <option value="">Seleccione una opción</option>
                    {% for id, genero in form.fields.pref_genero.choices %}
                        <option value="{{ id }}">{{ genero }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="content-test" id="content-2" data-id='2'>
            <h3>¿Qué tipo de terapia estás buscando?</h3>
            <div class="form-group">
                <select name="tipo_terapia" id="id_tipo_terapia" class="form-control">
                    <option value="">Seleccione una opción</option>
                    {% for id, tipo in form.fields.tipo_terapia.choices %}
                        <option value="{{ id }}">{{ tipo }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="content-test" id="content-3" data-id='3'>
            <h3>¿Tienes preferencia por alguna corriente teórica de psicología?</h3>
            <div class="form-group">
                {{ form.pref_corriente }}
            </div>
        </div>
        <div class="content-test" id="content-4" data-id='4'>
            <h3>Tengo diagnóstico o sospecha de:</h3>
            <div class="form-group">
                {{ form.diagnostico_sospecha }}
            </div>
        </div>
        <div class="content-test" id="content-5" data-id='5'>
            <h3>Motivo de búsqueda de psicólogo/a:</h3>
            <div class="form-group">
                {{ form.motivo_busqueda }}
            </div>
        </div>
        <div class="content-test" id="content-6" data-id='6'>
            <h3>¿Cuál es el rango de precio que puedes pagar por tu sesión de terapia?</h3>
            <div class="form-group">
                <select name="rango_precio" id="id_rango_precio" class="form-control">
                    <option value="">Seleccione una opción</option>
                    {% for id, precio in form.fields.rango_precio.choices %}
                        <option value="{{ id }}">{{ precio }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="content-test" id="content-7" data-id='7'>
            <h3>¿Con qué tipo de cobertura de salud cuentas?</h3>
            <div class="form-group">
                <select name="cobertura_salud" id="id_cobertura_salud" class="form-control">
                    <option value="">Seleccione una opción</option>
                    {% for id, cobertura in form.fields.cobertura_salud.choices %}
                        <option value="{{ id }}">{{ cobertura }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        
    </div>
    <div class="botones-test">
        <button type="button" class="test-back">Volver</button>
        <button type="button" class="test-next" id="btn-test">Continuar</button>
    </div>

    <div class="test-paciente-end">
        <div class="test-fin" data-id='8'>
            <p>Test terminado uwu, ¿quiere confirmar respuestas?</p>
            <button type="button" class="edit-anterior">Editar mis respuestas</button>
            <button type="submit" class="fin-test" id="btn-test">Encontrar psicólogo/a</button>
        </div>
    </div>
</form> {% endcomment %}

 <form method="POST" enctype="multipart/form-data" id="FormTestPaciente" class="FormTestPaciente">
    {% csrf_token %}
    <div class="test-paciente">
        <div class="content-test" id="content-1" data-id='1' style="display: block;">
            <h3>¿Tienes alguna preferencia sobre el género de tu psicólogo/a?</h3>
            <div class="form-group">
                {{ form.generopsicologo_idgenero }} 
            </div>
        </div>
        <div class="content-test" id="content-2" data-id='2'>
            <h3>¿En qué rango etario te encuentras?</h3>
            <div class="form-group">
                {{ form.rangoetario_idrangoetario}} 
            </div>
        </div>
        <div class="content-test" id="content-3" data-id='3'>
            <h3>¿Qué tipo de terapia estás buscando?</h3>
            <div class="form-group">
                {{ form.tiposesion_idtiposesion}} 
            </div>
        </div>
        <div class="content-test" id="content-4" data-id='4'>
            <h3>¿Tienes preferencia por alguna corriente teórica de psicología?</h3>
            <div class="form-group">
                {{ form.corriente_idcorriente }} 
            </div>
        </div>
        <div class="content-test" id="content-5" data-id='5'>
            <h3>Tengo diagnóstico o sospecha de:</h3>
            <div class="form-group">
                {{ form.diagnostico_iddiagnostico}} 
            </div>
        </div>
        <div class="content-test" id="content-6" data-id='6'>
            <h3>Motivo de búsqueda de psicólogo/a:</h3>
            <div class="form-group">
                {{ form.motivosesion_idmotivosesion }} 
            </div>
        </div>
        <div class="content-test" id="content-7" data-id='7'>
            <h3>¿Cuál es el rango de precio que puedes pagar por tu sesión de terapia?</h3>
            <div class="form-group">
                {{ form.rangoprecio_idrangoprecio }} 
            </div>
        </div>
        <div class="content-test" id="content-8" data-id='8'>
            <h3>¿Con qué tipo de cobertura de salud cuentas?</h3>
            <div class="form-group">
                {{ form.coberturasalud_idcobertura }} 
            </div>
        </div>
        
    </div>
    <div class="botones-test">
        <button type="button" class="test-back">Volver</button>
        <button type="button" class="test-next" id="btn-test">Continuar</button>
    </div>

    <div class="test-paciente-end">
        <div class="test-fin" data-id='9'>
            <p>Test terminado uwu, quiere confirmar respuestas?</p>
            <button type="button" class="edit-anterior">Editar mis respuestas</button>
            <button type="submit" class="fin-test" id="btn-test">Encontrar psicólogo/a</button>
        </div>

    </div>
</form>  

{% endblock content %}